spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_springtec
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_updates: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true
      exclude: static/**

# Habilitar/desabilitar api-docs swagger-ui
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    # Permitir la ruta de swagger-ui http://localhost:8080/doc/swagger-ui/index.html#/
    path: /doc/swagger-ui.html
  # Paquetes o clases a excanear
  paths-to-match: /api/v1/**
