-- MySQL Script generated by MySQL Workbench
-- Thu Nov 23 03:04:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema railway
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS railway ;

-- -----------------------------------------------------
-- Schema railway
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS railway DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE railway ;

-- -----------------------------------------------------
-- Table railway.role
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.role ;

CREATE TABLE IF NOT EXISTS railway.role (
                                            id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                            name VARCHAR(45) NOT NULL,
    PRIMARY KEY (id))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table railway.user
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.user ;

CREATE TABLE IF NOT EXISTS railway.user (
                                            id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                            role_id INT UNSIGNED NOT NULL,
                                            email VARCHAR(45) NOT NULL,
    password VARCHAR(240) NOT NULL,
    state CHAR(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (id),
    UNIQUE INDEX email_UNIQUE (email ASC) VISIBLE,
    INDEX fk_User_Role1_idx (role_id ASC) VISIBLE,
    CONSTRAINT fk_User_Role1
    FOREIGN KEY (role_id)
    REFERENCES railway.role (id))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table railway.image_user
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.image_user ;

CREATE TABLE IF NOT EXISTS railway.image_user (
                                                  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                  user_id INT UNSIGNED NOT NULL,
                                                  original_name VARCHAR(100) NOT NULL,
    extension_name VARCHAR(20) NOT NULL,
    content_type VARCHAR(20) NOT NULL,
    fake_name VARCHAR(100) NOT NULL,
    fake_extension_name VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    INDEX fk_image_user_user1_idx (user_id ASC) VISIBLE,
    CONSTRAINT fk_image_user_user1
    FOREIGN KEY (user_id)
    REFERENCES railway.user (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- -----------------------------------------------------
-- Table railway.help_desk
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.help_desk ;

CREATE TABLE IF NOT EXISTS railway.help_desk (
                                                 id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                 user_id INT UNSIGNED NOT NULL,
                                                 name VARCHAR(45) NOT NULL,
    father_lastname VARCHAR(45) NOT NULL,
    mother_lastname VARCHAR(45) NOT NULL,
    dni CHAR(8) NOT NULL,
    birth_date DATE NOT NULL,
    PRIMARY KEY (id),
    UNIQUE INDEX dni_UNIQUE (dni ASC) VISIBLE,
    INDEX fk_Tecnico_User_idx (user_id ASC) VISIBLE,
    CONSTRAINT fk_Tecnico_User1
    FOREIGN KEY (user_id)
    REFERENCES railway.user (id))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table railway.client
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.client ;

CREATE TABLE IF NOT EXISTS railway.client (
                                              id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                              user_id INT UNSIGNED NOT NULL,
                                              name VARCHAR(45) NOT NULL,
    father_lastname VARCHAR(45) NOT NULL,
    mother_lastname VARCHAR(45) NOT NULL,
    dni CHAR(8) NOT NULL,
    birth_date DATE NOT NULL,
    PRIMARY KEY (id),
    UNIQUE INDEX dni_UNIQUE (dni ASC) VISIBLE,
    INDEX fk_Tecnico_User_idx (user_id ASC) VISIBLE,
    CONSTRAINT fk_Tecnico_User0
    FOREIGN KEY (user_id)
    REFERENCES railway.user (id))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table railway.ticket_support
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.ticket_support ;

CREATE TABLE IF NOT EXISTS railway.ticket_support (
                                                      id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                      client_id INT UNSIGNED NOT NULL,
                                                      issue VARCHAR(45) NOT NULL,
    description VARCHAR(300) NOT NULL,
    date DATE NOT NULL,
    state CHAR(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (id),
    INDEX fk_Ticket_Soporte_Client1_idx (client_id ASC) VISIBLE,
    CONSTRAINT fk_Ticket_Soporte_Client1
    FOREIGN KEY (client_id)
    REFERENCES railway.client (id))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table railway.answer_support
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.answer_support ;

CREATE TABLE IF NOT EXISTS railway.answer_support (
                                                      id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                      ticket_support_id INT UNSIGNED NOT NULL,
                                                      help_desk_id INT UNSIGNED NOT NULL,
                                                      title VARCHAR(45) NOT NULL,
    answer VARCHAR(300) NOT NULL,
    date DATE NOT NULL,
    PRIMARY KEY (id),
    INDEX fk_answer_support_Ticket_Soporte1_idx (ticket_support_id ASC) VISIBLE,
    INDEX fk_answer_support_Help_Desk1_idx (help_desk_id ASC) VISIBLE,
    CONSTRAINT fk_answer_support_Help_Desk1
    FOREIGN KEY (help_desk_id)
    REFERENCES railway.help_desk (id),
    CONSTRAINT fk_answer_support_Ticket_Soporte1
    FOREIGN KEY (ticket_support_id)
    REFERENCES railway.ticket_support (id))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table railway.availability
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.availability ;

CREATE TABLE IF NOT EXISTS railway.availability (
                                                    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                    name VARCHAR(45) NOT NULL,
    state CHAR(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (id),
    UNIQUE INDEX name_UNIQUE (name ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table railway.category_services
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.category_services ;

CREATE TABLE IF NOT EXISTS railway.category_services (
                                                         id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                         name VARCHAR(45) NOT NULL,
    state CHAR(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (id),
    UNIQUE INDEX name_UNIQUE (name ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table railway.currency_type
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.currency_type ;

CREATE TABLE IF NOT EXISTS railway.currency_type (
                                                     id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                     symbol CHAR(4) NOT NULL,
    state CHAR(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (id),
    UNIQUE INDEX symbol_UNIQUE (symbol ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table railway.technical
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.technical ;

CREATE TABLE IF NOT EXISTS railway.technical (
                                                 id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                 user_id INT UNSIGNED NOT NULL,
                                                 name VARCHAR(45) NOT NULL,
    father_lastname VARCHAR(45) NOT NULL,
    mother_lastname VARCHAR(45) NOT NULL,
    dni CHAR(8) NOT NULL,
    birth_date DATE NOT NULL,
    lat DOUBLE NULL,
    lng DOUBLE NULL,
    working_status CHAR(1) NOT NULL DEFAULT '0',
    PRIMARY KEY (id),
    UNIQUE INDEX dni_UNIQUE (dni ASC) VISIBLE,
    INDEX fk_Tecnico_User_idx (user_id ASC) VISIBLE,
    CONSTRAINT fk_Tecnico_User
    FOREIGN KEY (user_id)
    REFERENCES railway.user (id))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table railway.review
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.review ;

CREATE TABLE IF NOT EXISTS railway.review (
                                              id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                              technical_id INT UNSIGNED NOT NULL,
                                              client_id INT UNSIGNED NOT NULL,
                                              number_stars INT(5) NOT NULL,
    title VARCHAR(100) NOT NULL,
    comment VARCHAR(250) NOT NULL,
    date DATE NOT NULL,
    hour TIME NOT NULL,
    PRIMARY KEY (id),
    INDEX fk_review_technical_id_idx (technical_id ASC) VISIBLE,
    INDEX fk_review_client_id_idx (client_id ASC) VISIBLE,
    CONSTRAINT fk_review_techncial_id1
    FOREIGN KEY (technical_id)
    REFERENCES railway.technical (id),
    CONSTRAINT fk_review_client_id1
    FOREIGN KEY (client_id)
    REFERENCES railway.client (id))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table railway.experience
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.experience ;

CREATE TABLE IF NOT EXISTS railway.experience (
                                                  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                  name VARCHAR(60) NOT NULL,
    PRIMARY KEY (id))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table railway.profession
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.profession ;

CREATE TABLE IF NOT EXISTS railway.profession (
                                                  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                  name VARCHAR(45) NOT NULL,
    state CHAR(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (id))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table railway.profession_availability
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.profession_availability ;

CREATE TABLE IF NOT EXISTS railway.profession_availability (
                                                               id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                               technical_id INT UNSIGNED NOT NULL,
                                                               profession_id INT UNSIGNED NOT NULL,
                                                               availability_id INT UNSIGNED NOT NULL,
                                                               experience_id INT UNSIGNED NOT NULL,
                                                               PRIMARY KEY (id),
    INDEX fk_technical_has_profession_profesion1_idx (profession_id ASC) VISIBLE,
    INDEX fk_technical_has_profession_Tecnico1_idx (technical_id ASC) VISIBLE,
    INDEX fk_technical_has_profession_Experience1_idx (experience_id ASC) VISIBLE,
    INDEX fk_technical_has_profession_availability1_idx (availability_id ASC) VISIBLE,
    CONSTRAINT fk_technical_has_profession_Experience1
    FOREIGN KEY (experience_id)
    REFERENCES railway.experience (id),
    CONSTRAINT fk_technical_has_profession_profesion1
    FOREIGN KEY (profession_id)
    REFERENCES railway.profession (id),
    CONSTRAINT fk_technical_has_profession_Tecnico1
    FOREIGN KEY (technical_id)
    REFERENCES railway.technical (id),
    CONSTRAINT fk_technical_has_profession_availability1
    FOREIGN KEY (availability_id)
    REFERENCES railway.availability (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;




-- -----------------------------------------------------
-- Table railway.services
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.services ;

CREATE TABLE IF NOT EXISTS railway.services (
                                                id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                category_services_id INT UNSIGNED NOT NULL,
                                                currency_type_id INT UNSIGNED NOT NULL,
                                                name VARCHAR(45) NOT NULL,
    description VARCHAR(255) NULL DEFAULT NULL,
    price DOUBLE(10,2) UNSIGNED NOT NULL,
    state CHAR(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (id),
    INDEX fk_services_Category_services1_idx (category_services_id ASC) VISIBLE,
    INDEX fk_services_currency_type_idx (currency_type_id ASC) VISIBLE,
    CONSTRAINT fk_services_Category_services1
    FOREIGN KEY (category_services_id)
    REFERENCES railway.category_services (id),
    CONSTRAINT fk_services_currency_type1
    FOREIGN KEY (currency_type_id)
    REFERENCES railway.currency_type (id))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table railway.service_type_availability
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.service_type_availability ;

CREATE TABLE IF NOT EXISTS railway.service_type_availability (
                                                                 id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                 profession_availability_id INT UNSIGNED NOT NULL,
                                                                 services_id INT UNSIGNED NOT NULL,
                                                                 PRIMARY KEY (id),
    INDEX fk_service_type_availability_profession_availability1_idx (profession_availability_id ASC) VISIBLE,
    INDEX fk_service_type_availability_services1_idx (services_id ASC) VISIBLE,
    CONSTRAINT fk_service_type_availability_profession_availability1
    FOREIGN KEY (profession_availability_id)
    REFERENCES railway.profession_availability (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT fk_service_type_availability_services1
    FOREIGN KEY (services_id)
    REFERENCES railway.services (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table railway.state_direct_request
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.state_direct_request ;

CREATE TABLE IF NOT EXISTS railway.state_direct_request (
                                                            id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                            name VARCHAR(45) NOT NULL,
    PRIMARY KEY (id))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table railway.direct_request
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.direct_request ;

CREATE TABLE IF NOT EXISTS railway.direct_request (
                                                      id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                      profession_availability_id INT UNSIGNED NOT NULL,
                                                      client_id INT UNSIGNED NOT NULL,
                                                      category_services_id INT UNSIGNED NOT NULL,
                                                      service_type_availability_id INT UNSIGNED NULL,
                                                      state_direct_request_id INT UNSIGNED NOT NULL,
                                                      latitude DOUBLE NOT NULL,
                                                      longitude DOUBLE NOT NULL,
                                                      title VARCHAR(80) NOT NULL,
    description VARCHAR(255) NOT NULL,
    state_invoice CHAR(1) NULL DEFAULT '0',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- CURENT_... cuando no se pase, se establecera en la hora actual
    answered_at TIMESTAMP NULL,
    resolved_at TIMESTAMP NULL,
    PRIMARY KEY (id),
    INDEX fk_direct_request_profession_availability1_idx (profession_availability_id ASC) VISIBLE,
    INDEX fk_direct_request_client1_idx (client_id ASC) VISIBLE,
    INDEX fk_direct_request_category_services1_idx (category_services_id ASC) VISIBLE,
    INDEX fk_direct_request_service_type_availability1_idx (service_type_availability_id ASC) VISIBLE,
    INDEX fk_direct_request_state_direct_request1_idx (state_direct_request_id ASC) VISIBLE,
    CONSTRAINT fk_direct_request_client1
    FOREIGN KEY (client_id)
    REFERENCES railway.client (id),
    CONSTRAINT fk_direct_request_category_services1
    FOREIGN KEY (client_id)
    REFERENCES railway.client (id),
    CONSTRAINT fk_direct_request_profession_availability1
    FOREIGN KEY (category_services_id)
    REFERENCES railway.category_services (id),
    CONSTRAINT fk_direct_request_service_type_availability1
    FOREIGN KEY (service_type_availability_id)
    REFERENCES railway.service_type_availability (id),
    CONSTRAINT fk_direct_request_state_direct_request_1
    FOREIGN KEY (state_direct_request_id)
    REFERENCES railway.state_direct_request (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table railway.image_upload
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.image_upload ;

CREATE TABLE IF NOT EXISTS railway.image_upload (
                                                    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                    direct_request_id INT UNSIGNED NOT NULL,
                                                    original_name VARCHAR(100) NOT NULL,
    extension_name VARCHAR(20) NOT NULL,
    content_type VARCHAR(20) NOT NULL,
    fake_name VARCHAR(100) NOT NULL,
    fake_extension_name VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    INDEX fk_img_firebase_direct_request_id_idx (direct_request_id ASC) VISIBLE,
    CONSTRAINT fk_img_firebase_direct_request_id1
    FOREIGN KEY (direct_request_id)
    REFERENCES railway.direct_request (id))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table railway.invoice
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.invoice ;

CREATE TABLE IF NOT EXISTS railway.invoice (
                                               id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                               direct_request_id INT UNSIGNED NOT NULL,
                                               task VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    price DOUBLE(10,2) UNSIGNED NOT NULL,
    date DATE NOT NULL,
    hour TIME NOT NULL,
    state CHAR(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (id),
    INDEX fk_invoice_direct_request_id_idx (direct_request_id ASC) VISIBLE,
    CONSTRAINT fk_invoice_direct_request_id1
    FOREIGN KEY (direct_request_id)
    REFERENCES railway.direct_request (id))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;




-- -----------------------------------------------------
-- Table railway.material
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.material ;

CREATE TABLE IF NOT EXISTS railway.material (
                                                id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                invoice_id INT UNSIGNED NOT NULL,
                                                name VARCHAR(100) NOT NULL,
    price DOUBLE(10,2) UNSIGNED NOT NULL,
    stock TINYINT UNSIGNED NOT NULL,
    state CHAR(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (id),
    INDEX fk_material_invoice_id_idx (invoice_id ASC) VISIBLE,
    CONSTRAINT fk_material_invoice_id1
    FOREIGN KEY (invoice_id)
    REFERENCES railway.invoice (id))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table railway.Profession_local
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.profession_local ;

CREATE TABLE IF NOT EXISTS railway.profession_local (
                                                        id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                        profession_availability_id INT UNSIGNED NOT NULL,
                                                        lat DOUBLE NULL,
                                                        lng DOUBLE NULL,
                                                        state CHAR(1) DEFAULT '1' NOT NULL,
    PRIMARY KEY (id),
    INDEX fk_Profession_local_profession_availability1_idx (profession_availability_id ASC) VISIBLE,
    CONSTRAINT fk_Profession_local_profession_availability1
    FOREIGN KEY (profession_availability_id)
    REFERENCES railway.profession_availability (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table railway.image_service
-- -----------------------------------------------------
DROP TABLE IF EXISTS railway.image_service ;

CREATE TABLE IF NOT EXISTS railway.image_service (
                                                     id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                     services_id INT UNSIGNED NOT NULL,
                                                     original_name VARCHAR(100) NOT NULL,
    extension_name VARCHAR(20) NOT NULL,
    content_type VARCHAR(20) NOT NULL,
    fake_name VARCHAR(100) NOT NULL,
    fake_extension_name VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    INDEX fk_image_service_services1_idx (services_id ASC) VISIBLE,
    CONSTRAINT fk_image_service_services1
    FOREIGN KEY (services_id)
    REFERENCES railway.services (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- ------- AVAILABILITY ----------- --
-- -------------------------------- --

INSERT INTO state_direct_request(name) VALUES ('Pendiente');
INSERT INTO state_direct_request(name) VALUES ('En proceso');
INSERT INTO state_direct_request(name) VALUES ('Cerrado');
INSERT INTO state_direct_request(name) VALUES ('Cancelado');
Insert into state_direct_request(name) values ("Solicitud de Cierre");

-- ------- AVAILABILITY ----------- --
-- -------------------------------- --

INSERT INTO availability(name) VALUES ('A domicilio');
INSERT INTO availability(name) VALUES ('En taller');

-- ------- PROFESSION ----------- --
-- -------------------------------- --

INSERT INTO profession(name) VALUES ('Mecánico');
INSERT INTO profession(name) VALUES ('Plomero');
INSERT INTO profession(name) VALUES ('Electricista');
INSERT INTO profession(name) VALUES ('Ingeniero de Software');
INSERT INTO profession(name) VALUES ('Diseñador Gráfico');


-- ------- PROFESSION ----------- --
-- -------------------------------- --

INSERT INTO role(name) VALUES ('CLIENT');
INSERT INTO role(name) VALUES ('TECHNICAL');
INSERT INTO role(name) VALUES ('HELPDESK');

-- ------- EXPERIENCE ----------- --
-- -------------------------------- --

INSERT INTO experience(name) VALUES ('Estudiante Universitario');
INSERT INTO experience(name) VALUES ('No titulado');
INSERT INTO experience(name) VALUES ('Técnico');
INSERT INTO experience(name) VALUES ('Ingeniero');

-- ------- CATEGORY SERVICE ----------- --
-- -------------------------------- --

INSERT INTO category_services(name) VALUES ('Limpieza');
INSERT INTO category_services(name) VALUES ('Revisión');
INSERT INTO category_services(name) VALUES ('Mantenimiento');
INSERT INTO category_services(name) VALUES ('Reparación');
INSERT INTO category_services(name) VALUES ('Instalación');

-- ------- CURRENCY TYPE ----------- --
-- -------------------------------- --

INSERT INTO currency_type(symbol) VALUES ('S/');
INSERT INTO currency_type(symbol) VALUES ('$');
INSERT INTO currency_type(symbol) VALUES ('€');






-- CALL ExistsAvailabilityProfessionExperience(3,7,5);
DELIMITER //
CREATE PROCEDURE ExistsAvailabilityProfessionExperience(
    IN p_availability_id INT,
    IN p_profession_id INT,
    IN p_experience_id INT
)
BEGIN
    DECLARE messages VARCHAR(255);
	SET messages = '';
    IF (
SELECT COUNT(*)
FROM availability
WHERE id = p_availability_id
    ) = 0 THEN
SET messages = CONCAT(messages,'La disponibilidad con id = ', p_availability_id, ' no existe; ');
END IF;

    IF (
SELECT COUNT(*)
FROM profession
WHERE id = p_profession_id
    ) = 0 THEN
SET messages = CONCAT(messages, 'La profesión con id = ', p_profession_id, ' no existe; ');
END IF;

    IF (
SELECT COUNT(*)
FROM experience
WHERE id = p_experience_id
    ) = 0 THEN
SET messages = CONCAT(messages, 'La experiencia con id = ', p_experience_id, ' no existe; ');
END IF;

SELECT messages AS result;
END //
DELIMITER ;


DELIMITER //

CREATE PROCEDURE UpdateTechnicalLocation(
    IN p_technicalId INT,
    IN p_latitude DECIMAL(10, 6),
    IN p_longitude DECIMAL(10, 6),
    IN p_workingStatus CHAR(1)
)
BEGIN
UPDATE technical
SET lat = p_latitude, lng = p_longitude
WHERE id = p_technicalId AND working_status = p_workingStatus;

SELECT ROW_COUNT() AS isUpdated;
END //

DELIMITER ;


DELIMITER //
CREATE PROCEDURE FilterTechnicalsAvailabilityNoInLocal(
    IN p_availabilityId INT,
    IN p_professionId INT,
    IN p_rango INT,
    IN p_latitude DECIMAL(10, 6),
    IN p_longitude DECIMAL(10, 6),
    IN p_workingStatus CHAR(1)
)
BEGIN
SELECT
    t.*
FROM
    technical t
        INNER JOIN
    profession_availability pa ON t.id = pa.technical_id
WHERE
        pa.availability_id = p_availabilityId
  AND pa.profession_id = p_professionId
  AND t.working_status = p_workingStatus  -- Consideramos solo técnicos activos
  AND (
              6371 * ACOS(
                          COS(RADIANS(p_latitude)) * COS(RADIANS(t.lat)) * COS(RADIANS(p_longitude) - RADIANS(t.lng))
                      + SIN(RADIANS(p_latitude)) * SIN(RADIANS(t.lat))
              )
          ) <= p_rango;
END //

DELIMITER ;

DELIMITER //
CREATE PROCEDURE FilterTechnicalsAvailabilityIsLocal(
    IN p_availabilityId INT,
    IN p_professionId INT,
    IN p_rango INT,
    IN p_latitude DECIMAL(10, 6),
    IN p_longitude DECIMAL(10, 6),
    IN p_state_local INT
)
BEGIN

SELECT DISTINCT
    t.*
FROM
    technical t
        INNER JOIN
    profession_availability pa ON t.id = pa.technical_id
        LEFT JOIN
    profession_local pl ON pa.id = pl.profession_availability_id
WHERE
        pa.profession_id = p_professionId
  AND pa.availability_id = p_availabilityId
  AND pl.state = p_state_local
  AND (
              6371 * ACOS(
                          COS(RADIANS(p_latitude)) * COS(RADIANS(COALESCE(pl.lat, t.lat))) * COS(RADIANS(p_longitude) - RADIANS(COALESCE(pl.lng, t.lng)))
                      + SIN(RADIANS(p_latitude)) * SIN(RADIANS(COALESCE(pl.lat, t.lat)))
              )
          ) <= p_rango;
END //

DELIMITER ;

DELIMITER //
CREATE PROCEDURE FilterNearbyAllTechnicals(
    IN p_professionId INT,
    IN p_rango INT,
    IN p_latitude DECIMAL(10, 6),
    IN p_longitude DECIMAL(10, 6),
    IN p_workingStatus CHAR(1)
)
BEGIN

SELECT DISTINCT
    t.*
FROM
    technical t
        INNER JOIN
    profession_availability pa ON t.id = pa.technical_id
        LEFT JOIN
    profession_local pl ON pa.id = pl.profession_availability_id
WHERE
        pa.profession_id = p_professionId
  AND t.working_status = p_workingStatus
  AND (
              6371 * ACOS(
                          COS(RADIANS(p_latitude)) * COS(RADIANS(COALESCE(pl.lat, t.lat))) * COS(RADIANS(p_longitude) - RADIANS(COALESCE(pl.lng, t.lng)))
                      + SIN(RADIANS(p_latitude)) * SIN(RADIANS(COALESCE(pl.lat, t.lat)))
              )
          ) <= p_rango;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE findAllByTechnicalIdAndDistintStateId(
    IN p_technical_id INT,
    IN p_state_id INT
)
BEGIN
SELECT
    dr.*
FROM direct_request dr
         INNER JOIN profession_availability pa ON dr.profession_availability_id = pa.id
WHERE pa.technical_id = p_technical_id AND dr.state_direct_request_id != p_state_id;
END //
DELIMITER ;



DELIMITER //
CREATE PROCEDURE findAllByTechnicalIdAndStateIdAndStateInvoiceId(
    IN p_technical_id INT,
    IN p_state_id INT,
    IN p_state_invoice_id INT
)
BEGIN
SELECT
    dr.*
FROM direct_request dr
         INNER JOIN profession_availability pa ON dr.profession_availability_id = pa.id
WHERE pa.technical_id = p_technical_id
  AND (
        (p_state_id = 2 AND dr.state_direct_request_id IN (2, 5))
        OR (p_state_id <> 2 AND dr.state_direct_request_id = p_state_id)
    )
  AND dr.state_invoice = p_state_invoice_id;
END //
DELIMITER ;



-- TRIGGERS
DELIMITER //
CREATE TRIGGER tr_direct_request_state_invoice
    BEFORE UPDATE ON railway.direct_request
    FOR EACH ROW
BEGIN
    IF NEW.state_invoice = '1' THEN
        SET NEW.answered_at = CURRENT_TIMESTAMP;
END IF;
END;
//

CREATE TRIGGER tr_direct_request_state_direct_request
    BEFORE UPDATE ON railway.direct_request
    FOR EACH ROW
BEGIN
    IF NEW.state_direct_request_id = 3 THEN
        SET NEW.resolved_at = CURRENT_TIMESTAMP;
END IF;
END;
//
DELIMITER ;

